### ISSUE TITLE
I'm getting this error while using $RefParser.derefernce in angular ionic

### ISSUE THREAD

**Issue by shivam-2701** [APIDevTools/json-schema-ref-parser#345]
``` bash
TypeError: Cannot read properties of undefined (reading 'sep')
    at convertPathToPosix (convert-path-to-posix.js:12:81)
    at Object.resolve (url.js:53:64)
    at $RefParser._callee$ (index.js:101:25)
    at tryCatch (index.js:2:1)
    at Generator.<anonymous> (index.js:2:1)
    at Generator.next (index.js:2:1)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _next (asyncToGenerator.js:25:1)
    at asyncToGenerator.js:32:1
    at new ZoneAwarePromise (zone.js:913:33)
    at $RefParser.<anonymous> (asyncToGenerator.js:21:1)
    at $RefParser.parse (index.js:137:6)
    at $RefParser._callee2$ (index.js:145:24)
    at tryCatch (index.js:2:1)
    at Generator.<anonymous> (index.js:2:1)
    at Generator.next (index.js:2:1)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _next (asyncToGenerator.js:25:1)
    at asyncToGenerator.js:32:1
    at new ZoneAwarePromise (zone.js:913:33)
    at $RefParser.<anonymous> (asyncToGenerator.js:21:1)
    at $RefParser.resolve (index.js:153:6)
    at $RefParser._callee4$ (index.js:181:24)
    at tryCatch (index.js:2:1)
    at Generator.<anonymous> (index.js:2:1)
    at Generator.next (index.js:2:1)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _next (asyncToGenerator.js:25:1)
    at asyncToGenerator.js:32:1
    at new ZoneAwarePromise (zone.js:913:33)
    at $RefParser.<anonymous> (asyncToGenerator.js:21:1)
    at $RefParser.dereference (index.js:189:6)
    at Function.dereference (index.js:176:37)
    at EntityFieldsMappingUtils.<anonymous> (entity-fields-mapping-utils.ts:29:41)
    at step (main.js:75053:23)
    at Object.next (main.js:75034:53)
    at main.js:75028:71
    at new ZoneAwarePromise (zone.js:913:33)
    at push.qKqo.__awaiter (main.js:75024:12)
    at push.qKqo.EntityFieldsMappingUtils.parseJSONSchema (entity-fields-mapping-utils.ts:26:110)
    at EntityFieldsMappingUtils.<anonymous> (entity-fields-mapping-utils.ts:156:34)
    at step (main.js:75053:23)
    at Object.next (main.js:75034:53)
    at main.js:75028:71
    at new ZoneAwarePromise (zone.js:913:33)
    at push.qKqo.__awaiter (main.js:75024:12)
    at push.qKqo.EntityFieldsMappingUtils.buildFieldMapping (entity-fields-mapping-utils.ts:152:61)
    at ItemImportHelper.<anonymous> (item-import-helper.ts:252:63)
    at step (main.js:8956:23)
    at Object.next (main.js:8937:53)
```

**Comment by jonluca** [comment]
I fixed this specific issue, but I'm wondering if you'll need to polyfill path for it to properly work

**Comment by shivam-2701** [comment]
Can you please tell me or point out some resources to set polyfill path in my angular ionic project, I am new to this... Any help is much appreciated

**Comment by shivam-2701** [comment]
> Does the latest version work for you?

It got fixed in the latest version, Thank you very much Sir
